### PR TITLE
Added flag icons to language switcher

### PR DESCRIPTION
**Pull request by blackfoxtr**
Hello

I've added flag icons to language switcher using `stijnvanouplines/blade-country-flags` package. Also added `use_emoji` and `flag` parameter to `available_locales` array.

Hope that it will be useful.

Thank you

### CODE REVIEW

**Comment by musa11971** [comment]
Relates to #3 

Hi, thanks for this! Tried testing it out, however I keep running into the same exception, any ideas?
Screenshot 2023-05-22 at 11-29-21 Svg by name flag-1x1-gb from set default not found

PS, since this is a breaking change (new config format), let's remove the emoji option all together. I'd rather just keep support for the new blade flag icons. 

And for your changes in LanguageLineResource, they are also fine, but do you mind removing the commented code? I don't see a reason to keep it there.

Thanks!

**Comment by blackfoxtr** [comment]
Hello
My mistake, i didn't made changes directly on package but copy/paste some stuff from working copy.
I think i was able to do the stuff you have asked for. 
It's my second contribution to day to opensource. Hopefully i did it right this time :)
Thank you.

**Comment by musa11971** [comment]
Tesekkur ederim @blackfoxtr - your contribution has been very valuable and will be merged. I will be tagging a new major release since these changes are not backwards compatible

**Comment by blackfoxtr** [comment]
Önemli değil @musa11971 thank you for your kind words.

**Pull request merged**
